services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    container_name: shipment_php

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - php
    container_name: shipment_nginx

  mysql:
    image: mysql:8
    container_name: shipment_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shipment
      MYSQL_USER: shipment
      MYSQL_PASSWORD: shipment
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
